export const pricingCategories = [
  {
    slug: "web-offers",
    title: "Website Services",
    description:
      "Conversion-focused website packages, from landing pages to full business sites and custom builds.",
  },
  {
    slug: "monthly-retainers",
    title: "Brand Content Retainers",
    description:
      "Ongoing video and content systems for businesses that need consistent monthly output.",
  },
  {
    slug: "one-off-projects",
    title: "Video Projects",
    description:
      "Production and post packages for focused campaigns and standalone video deliverables.",
  },
];

export const pricingPackages = [
  {
    slug: "starter-content-pack",
    name: "Starter Content Pack",
    category: "monthly-retainers",
    billingType: "monthly",
    startingPrice: 900,
    currency: "CAD",
    priceRange: [900, 1200],
    includes: [
      "4 short-form videos / month",
      "1 shoot session",
      "Basic editing and captions",
      "1 light revision round",
    ],
    featured: false,
    customQuoteRequired: false,
    poster: {
      webp1440: "/posters/pricing/starter-content-pack-1440.webp",
      webp960: "/posters/pricing/starter-content-pack-960.webp",
      jpg1440: "/posters/pricing/starter-content-pack-1440.jpg",
      jpg960: "/posters/pricing/starter-content-pack-960.jpg",
      alt: "Cinematic camera silhouetted on a tripod under a single copper light beam, against dark teal void.",
    },
  },
  {
    slug: "growth-content-pack",
    name: "Growth Content Pack",
    category: "monthly-retainers",
    billingType: "monthly",
    startingPrice: 1700,
    currency: "CAD",
    priceRange: [1700, 2200],
    includes: [
      "8 short-form videos / month",
      "1-2 shoot sessions",
      "Stronger edit polish",
      "Simple social cutdowns",
      "Priority over Starter clients",
    ],
    featured: true,
    customQuoteRequired: false,
    poster: {
      webp1440: "/posters/pricing/growth-content-pack-1440.webp",
      webp960: "/posters/pricing/growth-content-pack-960.webp",
      jpg1440: "/posters/pricing/growth-content-pack-1440.jpg",
      jpg960: "/posters/pricing/growth-content-pack-960.jpg",
      alt: "Layered editing timeline tracks glowing in copper and teal against dark studio space.",
    },
  },
  {
    slug: "brand-engine-pack",
    name: "Brand Engine Pack",
    category: "monthly-retainers",
    billingType: "monthly",
    startingPrice: 2900,
    currency: "CAD",
    priceRange: [2900, 3600],
    includes: [
      "12 short-form videos / month",
      "15-20 story assets",
      "Multiple shoot blocks",
      "Planning and batching support",
      "Faster turnaround",
    ],
    featured: false,
    customQuoteRequired: false,
    poster: {
      webp1440: "/posters/pricing/brand-engine-pack-1440.webp",
      webp960: "/posters/pricing/brand-engine-pack-960.webp",
      jpg1440: "/posters/pricing/brand-engine-pack-1440.jpg",
      jpg960: "/posters/pricing/brand-engine-pack-960.jpg",
      alt: "Network of glowing copper nodes connected by teal filament lines, suggesting a content engine.",
    },
  },
  {
    slug: "single-reel-social-ad",
    name: "Single Reel / Social Ad",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 300,
    currency: "CAD",
    priceRange: [300, 450],
    includes: [
      "Filmed + edited short-form piece",
      "Social platform export",
      "Basic caption styling",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "half-day-shoot-edit",
    name: "Half-day Shoot + Edit",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 750,
    currency: "CAD",
    priceRange: [750, 1000],
    includes: [
      "One efficient production block",
      "Content batching from one location",
      "Edited deliverables for social",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "full-day-shoot-edit",
    name: "Full-day Shoot + Edit",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 1350,
    currency: "CAD",
    priceRange: [1350, 1800],
    includes: [
      "Full-day capture",
      "Higher deliverable volume",
      "Multi-scene coverage",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "promo-brand-film",
    name: "Promo / Brand Film",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 1500,
    currency: "CAD",
    priceRange: [1500, 3000],
    includes: [
      "Cinematic promo build",
      "Pre-production alignment",
      "Custom edit approach",
    ],
    featured: false,
    customQuoteRequired: true,
  },
  {
    slug: "short-form-edit",
    name: "Short-form Edit",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 90,
    currency: "CAD",
    priceRange: [90, 180],
    includes: [
      "Edit only — you supply the footage",
      "Up to ~60 seconds (Reels / TikTok / Shorts)",
      "Cuts, captions, music, basic color and sound",
      "1 revision round",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "long-form-edit",
    name: "Long-form Edit",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 250,
    currency: "CAD",
    priceRange: [250, 500],
    includes: [
      "Edit only — you supply the footage",
      "5–15 minute video (YouTube / interview style)",
      "Story pacing, B-roll placement, captions",
      "Color and sound polish",
      "1 revision round",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "podcast-episode-edit",
    name: "Podcast Episode Edit",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 150,
    currency: "CAD",
    priceRange: [150, 300],
    includes: [
      "Multicam sync + audio cleanup",
      "Chapter markers and basic graphics",
      "Light B-roll / cutaway insertion",
      "Short-form clip pull (1 included)",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "brand-promo-edit",
    name: "Brand / Promo Edit",
    category: "one-off-projects",
    billingType: "one-off",
    startingPrice: 400,
    currency: "CAD",
    priceRange: [400, 900],
    includes: [
      "Edit only — you supply A-roll and B-roll",
      "Narrative-paced 30–90s promo cut",
      "Music, sound design, color grade",
      "Title cards / lower thirds",
      "2 revision rounds",
    ],
    featured: false,
    customQuoteRequired: false,
  },
  {
    slug: "landing-page-sprint",
    name: "Landing Page Sprint",
    category: "web-offers",
    billingType: "project",
    startingPrice: 650,
    currency: "CAD",
    priceRange: [650, 900],
    includes: [
      "1 custom landing page",
      "Responsive build",
      "Contact form",
      "Basic SEO setup",
      "1 revision round",
    ],
    featured: false,
    customQuoteRequired: false,
    poster: {
      webp1440: "/posters/pricing/landing-page-sprint-1440.webp",
      webp960: "/posters/pricing/landing-page-sprint-960.webp",
      jpg1440: "/posters/pricing/landing-page-sprint-1440.jpg",
      jpg960: "/posters/pricing/landing-page-sprint-960.jpg",
      alt: "Single glowing rectangular page panel floating in dark teal void with copper rim light.",
    },
  },
  {
    slug: "starter-website",
    name: "Starter Website",
    category: "web-offers",
    billingType: "project",
    startingPrice: 1200,
    currency: "CAD",
    priceRange: [1200, 1700],
    includes: [
      "3-5 pages",
      "Responsive design",
      "Contact form",
      "Basic SEO structure",
      "1-2 revision rounds",
    ],
    featured: false,
    customQuoteRequired: false,
    poster: {
      webp1440: "/posters/pricing/starter-website-1440.webp",
      webp960: "/posters/pricing/starter-website-960.webp",
      jpg1440: "/posters/pricing/starter-website-1440.jpg",
      jpg960: "/posters/pricing/starter-website-960.jpg",
      alt: "Three glowing page panels stacked in 3D depth, lit by copper and teal.",
    },
  },
  {
    slug: "business-website",
    name: "Business Website",
    category: "web-offers",
    billingType: "project",
    startingPrice: 2200,
    currency: "CAD",
    priceRange: [2200, 3000],
    includes: [
      "5-8 pages",
      "Service structure + content hierarchy",
      "Lead capture forms",
      "Basic integrations",
      "2 revision rounds",
    ],
    featured: true,
    customQuoteRequired: false,
    poster: {
      webp1440: "/posters/pricing/business-website-1440.webp",
      webp960: "/posters/pricing/business-website-960.webp",
      jpg1440: "/posters/pricing/business-website-1440.jpg",
      jpg960: "/posters/pricing/business-website-960.jpg",
      alt: "Abstract analytics dashboard with rising bar columns and an ascending line graph in copper and teal.",
    },
  },
  {
    slug: "custom-website-advanced-build",
    name: "Custom Website / Advanced Build",
    category: "web-offers",
    billingType: "project",
    startingPrice: null,
    currency: "CAD",
    priceRange: null,
    includes: [
      "Advanced animations",
      "Custom CMS",
      "Ecommerce or dashboards",
      "Heavy integrations",
    ],
    featured: false,
    customQuoteRequired: true,
    poster: {
      webp1440: "/posters/pricing/custom-website-advanced-build-1440.webp",
      webp960: "/posters/pricing/custom-website-advanced-build-960.webp",
      jpg1440: "/posters/pricing/custom-website-advanced-build-1440.jpg",
      jpg960: "/posters/pricing/custom-website-advanced-build-960.jpg",
      alt: "Architectural wall of layered translucent panels lit in copper and teal, suggesting custom system modules.",
    },
  },
];

export const addOns = [
  { name: "Drone footage", startingPrice: 200, priceRange: [200, 350] },
  { name: "Extra revision round", startingPrice: 75, priceRange: [75, 125] },
  { name: "Rush delivery", label: "+25% to +35%" },
  { name: "Extra cut / version", startingPrice: 75, priceRange: [75, 150] },
  { name: "Raw footage handoff", startingPrice: 200, priceRange: [200, 350] },
  {
    name: "Thumbnail / cover design",
    startingPrice: 20,
    priceRange: [20, 40],
  },
  { name: "Travel fee", customQuoteRequired: true },
  { name: "Copy support", startingPrice: 100, priceRange: [100, 300] },
  {
    name: "Additional website page",
    startingPrice: 150,
    priceRange: [150, 300],
  },
  {
    name: "Monthly monitoring / support",
    startingPrice: 100,
    priceRange: [100, 300],
  },
];
