/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 clapperboard.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Clapperboard(props) {
  const { nodes, materials } = useGLTF("/models/clapperboard.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, -0.058, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.75}
      >
        <mesh
          geometry={nodes.Clapperboard_Clapperboard_0.geometry}
          material={materials.Clapperboard}
          position={[0, 0.012, 0]}
        />
      </group>
      <mesh
        geometry={nodes.ClapperboardFlap_ClapperboardFlap_0.geometry}
        material={materials.ClapperboardFlap}
        position={[-0.164, 0.058, 0]}
        rotation={[-Math.PI / 2, -0.436, 0]}
        scale={0.025}
      />
    </group>
  );
}

useGLTF.preload("/models/clapperboard.glb");
